name: flutter_widget_list
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to:
version: 1.0.0+1

environment:
  sdk: "3.0.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fluttertoast: ^8.2.2
  flutter_redux: ^0.8.2
#  fish_redux: ^0.3.7

#  json_annotation: ^2.0.0
#  analyzer: ^0.33.6+1

  sqflite: ^2.0.0+4
  url_launcher: ^6.0.10

dev_dependencies:
#  build_runner: ^1.0.0
#  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - images/
  uses-material-design: true
